spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haocai_management?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

logging:
  level:
    com.haocai.management: debug